#!/usr/bin/python

import os

#os.system("onecodex --api-key API_KEY upload --no-prompt Ambree_des_Brigands_du_Jorat_R1.fastq.gz") Ambree_des_Brigands_du_Jorat_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_Salamandre_R1.fastq.gz La_Salamandre_R2.fastq.gz")
os.system("onecodex --api-key API_KEY upload --no-prompt Chimay_Red_Cap_R1.fastq.gz Chimay_Red_Cap_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Delirium_Tremens_R1.fastq.gz Delirium_Tremens_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Trois_Dames_R1.fastq.gz Trois_Dames_R2.fastqos.system(.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Orval_R1.fastq.gz Orval_R2.os.system(fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_cotta_bionda_R1.fastq.gz La_cotta_os.system(bionda_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Hoppy_Couple_R1.fastq.gz Hoppy_Couple_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Waldbier_2014_Wienerwald_R1.fastq.gz Waldbier_2014_Wienerwald_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Valaisanne_Amrich_R1.fastq.gz Valaisanne_Amrich_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_Gessienne_Blanche_R1.fastq.gz Brasserie_Gessienne_Blanche_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Mateo_21_R1.fastq.gz Mateo_21_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Docteur_Gabs_Pepite_R1.fastq.gz Docteur_Gabs_Pepite_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Docteur_Gabs_Tempete_R1.fastq.gz Docteur_Gabs_Tempete_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_Nebuleuse_Embuscade_R1.fastq.gz La_Nebuleuse_Embuscade_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Hackuarium_Fakufaku_R1.fastq.gz Hackuarium_Fakufaku_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Calvinus_Blanche_R1.fastq.gz Calvinus_Blanche_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Les_Muraille_Pieuse_R1.fastq.gz Les_Muraille_Pieuse_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Homebrew_Roter_Baron_R1.fastq.gz Homebrew_Roter_Baron_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Docteur_Gabs_Houleuse_R1.fastq.gz Docteur_Gabs_Houleuse_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Coudres_Pale_Ale_R1.fastq.gz Coudres_Pale_Ale_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Homebrew_Amber_Ale_R1.fastq.gz Homebrew_Amber_Ale_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Homebrew_SquareBeer_R1.fastq.gz Homebrew_SquareBeer_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_Nebuleuse_Malt_Capone_R1.fastq.gz La_Nebuleuse_Malt_Capone_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_Nebuleuse_Stirling_R1.fastq.gz La_Nebuleuse_Stirling_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Bieraria_Tschlin_BE_R1.fastq.gz Bieraria_Tschlin_BE_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Chimay_Tripel_R1.fastq.gz Chimay_Tripel_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_DuPont_BioLegere_R1.fastq.gz Brasserie_DuPont_BioLegere_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_dAyent_Celsius_Folamour_R1.fastq.gz Brasserie_dAyent_Celsius_Folamour_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Coudres_Blonde_R1.fastq.gz Coudres_Blonde_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_Nebuleuse_ChichaBeer_experimental_R1.fastq.gz La_Nebuleuse_ChichaBeer_experimental_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_Mule_Browney_R1.fastq.gz La_Mule_Browney_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt La_Montheysanne_R1.fastq.gz La_Montheysanne_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_du_Griffon_La_Fourbe_R1.fastq.gz Brasserie_du_Griffon_La_Fourbe_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_Sierrvoise_Noire_R1.fastq.gz Brasserie_Sierrvoise_Noire_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasseurs_de_Volleges_La_Tourbillon_R1.fastq.gz Brasseurs_de_Volleges_La_Tourbillon_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_du_Vieux_Chemin_La_Prudencia_R1.fastq.gz Brasserie_du_Vieux_Chemin_La_Prudencia_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_Tardiv_R1.fastq.gz Brasserie_Tardiv_R2.fastq.gz") 
os.system("onecodex --api-key API_KEY upload --no-prompt Brasserie_des_5_quatre_mille_Biere_de_Zinal_R1.fastq.gz Brasserie_des_5_quatre_mille_Biere_de_Zinal_R2.fastq.gz") 
